server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://106.14.5.63:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 594Caoyizheng!
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # OSS相关配置信息
#  LTAI5t8UgGRGES3tW6TZj9Hz
#  UGQzBlNWqTx5MSOVh8PMLb65f2PDoz
  aliyun:
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
      accessKeyId: LTAI5t8UgGRGES3tW6TZj9Hz # 访问身份验证中用到用户标识
      accessKeySecret: UGQzBlNWqTx5MSOVh8PMLb65f2PDoz # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
      bucketName: 2021mall # oss的存储空间
      policy:
        expire: 300 # 签名有效期(S)
      maxSize: 10 # 上传文件大小(M)
      callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
      dir:
        prefix: product_brand/ # 上传文件夹路径前缀